=== DataSQRL/sqrl/sqrl-tools/sqrl-config/src/main/resources/jsonSchema/tableConfig.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "flink": {
      "type": "object",
      "additionalProperties": true
    },
    "table": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "primary-key": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        },
        "partition-key": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        },
        "timestamp": {
          "type": "string"
        },
        "watermark-millis": {
          "oneOf": [
            {
              "type": "string",
              "pattern": "^[0-9]*$"
            },
            {
              "type": "integer",
              "minimum": 0
            }
          ]
        }
      },
      "required": ["type"],
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": { "type": { "const": "source" } }
          },
          "then": {
            "required": ["primary-key", "timestamp"]
          }
        }
      ]
    },
    "metadata": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "required": ["version", "table"]
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/repository/datasqrl-central/submission.table.json
{
  "version": 1,
  "flink" : {
    "format" : "json",
    "path" : "/mnt/build/data",
    "source.monitor-interval" : 0,
    "connector" : "filesystem",
    "source.path.regex-pattern" : "to be determined"
  },
  "table" : {
    "type" : "source",
    "primary-key" : ["_uuid", "submissionTime"],
    "timestamp" : "submissionTime",
    "watermark-millis" : "1"
  },
  "metadata" : {
    "_uuid" : {
      "attribute" : "secure.Uuid()"
    }
  }
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/dagplanner/ecommerce/customer.table.json
{
  "version": 1,
  "flink" : {
    "format" : "json",
    "path" : "file:/mock",
    "source.monitor-interval" : 10000,
    "connector" : "filesystem",
    "source.path.regex-pattern" : ""
  },
  "table" : {
    "type" : "source",
    "timestamp" : "_ingest_time",
    "primary-key" : ["customerid", "email", "name", "lastUpdated"]
  },
  "metadata" : {
    "_ingest_time" : {
      "attribute" : "proctime()"
    }
  }
}
