=== DataSQRL/sqrl/sqrl-tools/sqrl-config/src/main/resources/jsonSchema/tableConfig.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "flink": {
      "type": "object",
      "additionalProperties": true
    },
    "table": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "primary-key": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        },
        "partition-key": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        },
        "timestamp": {
          "type": "string"
        },
        "watermark-millis": {
          "oneOf": [
            {
              "type": "string",
              "pattern": "^[0-9]*$"
            },
            {
              "type": "integer",
              "minimum": 0
            }
          ]
        }
      },
      "required": ["type"],
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": { "type": { "const": "source" } }
          },
          "then": {
            "required": ["primary-key", "timestamp"]
          }
        }
      ]
    },
    "metadata": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "required": ["version", "table"]
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/logging/default/mock/data.table.json
{
  "version": 1,
  "flink" : {
    "connector" : "datagen",
    "number-of-rows": "10",
    "fields.id.kind": "sequence",
    "fields.id.start": "0",
    "fields.epoch_timestamp.kind": "sequence",
    "fields.epoch_timestamp.start": "1719318565",
    "fields.some_value.kind": "random"
  },
  "table" : {
    "type" : "source",
    "primary-key" : ["id"],
    "timestamp" : "timestamp",
    "watermark-millis" : "1"
  },
  "metadata" : {
    "timestamp" : {
      "attribute" : "time.epochMilliToTimestamp(epoch_timestamp)"
    }
  }
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/seedshop-avro/seedshop-avro/orders.table.json
{
  "version": 1,
  "flink" : {
    "format" : "avro",
    "bootstrap.servers": "${sys:datasqrl.kafka_servers}",
    "group.id": "datasqrl-orders",
    "connector" : "kafka"
  },
  "table" : {
    "type" : "source",
    "primary-key" : ["id", "time"],
    "timestamp" : "_source_time",
    "watermark-millis" : "0"
  },
  "metadata" : {
    "_source_time" : {
      "attribute" : "timestamp",
      "type": "TIMESTAMP_WITH_LOCAL_TIME_ZONE(3)"
    }
  }

}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/duckdb/data/data.table.json
{
  "flink" : {
    "format" : "flexible-json",
    "path" : "/data/data.jsonl",
    "source.monitor-interval" : 1,
    "connector" : "filesystem"
  },
  "metadata" : {
    "_ingest_time" : {
      "attribute" : "proctime()"
    },
    "_uuid" : {
      "attribute" : "secure.Uuid()"
    }
  },
  "version" : 1,
  "table" : {
    "type" : "source",
    "primary-key" : "_uuid",
    "timestamp" : "_ingest_time"
  }
}

=== DataSQRL/sqrl/sqrl-tools/sqrl-config/src/test/resources/config/tableConfig/tableConfigFull.json
{
  "version": 1,
  "flink" : {
    "format" : "json",
    "path" : "file:/mock",
    "source.monitor-interval" : 10000,
    "connector" : "filesystem",
    "source.path.regex-pattern" : ""
  },
  "table" : {
    "type" : "source",
    "primary-key" : ["customerid", "lastUpdated"],
    "partition-key" : ["customerid"],
    "timestamp" : "timestamp",
    "watermark-millis" : "1"
  },
  "metadata" : {
    "timestamp" : {
      "attribute" : "time.epochToTimestamp(lastUpdated)"
    }
  }
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/postgres-log/mock/data.table.json
{
  "version": 1,
  "flink" : {
    "connector" : "datagen",
    "number-of-rows": "10",
    "fields.ID.kind": "sequence",
    "fields.ID.start": "0",
    "fields.ID.end": "9",
    "fields.EPOCH_TIMESTAMP.kind": "sequence",
    "fields.EPOCH_TIMESTAMP.start": "1719318565000",
    "fields.EPOCH_TIMESTAMP.end": "1719319565000",
    "fields.SOME_VALUE.kind": "random",
    "fields._uuid.kind": "random"
  },
  "table" : {
    "type" : "source",
    "primary-key" : ["ID"],
    "timestamp" : "TIMESTAMP",
    "watermark-millis" : "1"
  },
  "metadata" : {
    "TIMESTAMP" : {
      "attribute" : "time.epochMilliToTimestamp(EPOCH_TIMESTAMP)"
    },
    "event_time" : {
      "attribute" : "time.epochMilliToTimestamp(EPOCH_TIMESTAMP)"
    }
  }
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/seedshop-tutorial/seedshop/customers.table.json
{
  "version": 1,
  "flink" : {
    "format" : "flexible-json",
    "path" : "${DATA_PATH}/customers.jsonl",
    "connector" : "filesystem"
  },
  "table" : {
    "type" : "source",
    "primary-key" : ["id", "changed_on"],
    "timestamp" : "timestamp",
    "watermark-millis" : "1"
  },
  "metadata" : {
    "timestamp" : {
      "attribute" : "time.epochMilliToTimestamp(changed_on)"
    }
  }
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/dagplanner/ecommerce/product.table.json
{
  "version": 1,
  "flink" : {
    "format" : "json",
    "path" : "file:/mock",
    "source.monitor-interval" : 10000,
    "connector" : "filesystem",
    "source.path.regex-pattern" : ""
  },
  "table" : {
    "type" : "source",
    "timestamp" : "_ingest_time",
    "primary-key" : ["productid", "name", "description", "category"]
  },
  "metadata" : {
    "_ingest_time" : {
      "attribute" : "proctime()"
    }
  }
}

=== DataSQRL/sqrl/sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/simple-with-bigint-support/ecommerce/orders.table.json
{
  "version": 1,
  "flink" : {
    "format" : "flexible-json",
    "path" : "${DATA_PATH}/orders.jsonl",
    "source.monitor-interval" : 10000,
    "connector" : "filesystem"
  },
  "table" : {
    "type" : "source",
    "timestamp" : "_ingest_time",
    "primary-key" : ["id", "customerid", "time"]
  },
  "metadata" : {
    "_ingest_time" : {
      "attribute" : "proctime()"
    }
  }
}
